id: A1A8D1E52
title: Aspiration for All Lives to Come
type: translation
pechas:
- I100AB09C
- IBFACAED5
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:54:51.485085
  last_modified_at: 2023-01-04 11:54:51.485091
  collections:
  - Fourth Dodrupchen Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I100AB09C/43BA: CF81
  IBFACAED5/7DFD: CF81
